### ISSUE TITLE
See nginx logs is `STDOUT` and `STDERR`

### ISSUE THREAD

**Issue by shaardie** [iotec-gmbh/docker-nginx-certbot#7]
It would be great if nginx would redirect its logs to `STDOUT` and `STDERR` as well. So I would be able to see them using `docker logs...`

My current workaround is

    docker exec -it <container> tail -f /var/log/nginx/access.log /var/log/nginx/error.log

**Comment by lkiesow** [comment]
nginx-Konfiguration:

    access_log /dev/stdout;

**Comment by shaardie** [comment]
Seems to work. Closing again...
